### ISSUE TITLE
meta-amlogic compile issue

### ISSUE THREAD

**Issue by floragui** [linux-meson/meta-amlogic#5]
when compile Yocoto with meta-amlogic machine, I met the following compile error

````
ERROR: Unable to install packages. Command '/home/floragui/code/Yocto/meta-amlogic/build/tmp/sysroots/x86_64-linux/usr/bin/smart --quiet --data-dir=/home/floragui/code/Yocto/meta-amlogic/build/tmp/work/odroidc1-poky-linux-gnueabi/core-image-base/1.0-r0/rootfs/var/lib/smart install -y psplash@cortexa5hf_vfp_neon packagegroup-base-extended@odroidc1 run-postinsts@all packagegroup-core-boot@odroidc1 locale-base-en-us@cortexa5hf_vfp_neon locale-base-en-gb@cortexa5hf_vfp_neon' returned 1:
error: Can't install libamcodec-v2014.05.27+git0+143e73d6d7-r3@odroidc1: no package provides libstdc++.so


ERROR: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/floragui/code/Yocto/meta-amlogic/build/tmp/work/odroidc1-poky-linux-gnueabi/core-image-base/1.0-r0/temp/log.do_rootfs.21775
ERROR: Task 7 (/home/floragui/code/Yocto/meta-amlogic/poky/meta/recipes-core/images/core-image-base.bb, do_rootfs) failed with exit code '1'
````

First time i also see WARNING like this:
WARNING: QA Issue: libamcodec requires libm.so, libstdc++.so, libc.so, but no providers in its RDEPENDS [file-rdeps] 

does anyone meet this before? how to solve the issue?

**Comment by graugans** [comment]
Can you please provide the info screen which is shown after recipe parsing which contains machine and and distro information + used layers and git SHA1s?

Yes, the QA Warnings are on the TODO list. see #1 
It looks like you are using ``PACKAGE_CLASSES ?="package_rpm"`` in conf/local.conf isn't it?

I am using ipk in most cases. Can you please retry with ipk please?
```
PACKAGE_CLASSES ?= "package_ipk"
```

**Comment by floragui** [comment]
Thanks, it works, didn't report "no package provides libstdc++.so" again.

**Comment by rzr** [comment]
I've observed this on poky dizzy while building recipes-core/images/wetek-image-minimal.bb on odroidc1
